import type { Metadata } from "next";
import Header from "./components/header";
import Footer from "./components/footer";

import "./styles/all.css"
import "./styles/blog.css"
import "./styles/common.css" 
import "./styles/contact.css"
import "./styles/index.css" 
import "./styles/singleBlog.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
